function [rframes] = ISIcross(isiTimeFrames, ifi) 
        rframes = randi([0 isiTimeFrames*2]);
        offlimits = [round((1:8)*0.25/ifi)];
        pmv = round(0.05/ifi);
        
        % we ensure that the ISI is never a multiple of 0.25s +- 0.05 so
        % that we always have following trials in a new condition.
        while (offlimits(1)-pmv <= rframes && rframes <= offlimits(1)+pmv) ...
           || (offlimits(2)-pmv <= rframes && rframes <= offlimits(2)+pmv) ...
           || (offlimits(3)-pmv <= rframes && rframes <= offlimits(3)+pmv) ...
           || (offlimits(4)-pmv <= rframes && rframes <= offlimits(4)+pmv) ...
           || (offlimits(5)-pmv <= rframes && rframes <= offlimits(5)+pmv) ...
           || (offlimits(6)-pmv <= rframes && rframes <= offlimits(6)+pmv) ...
           || (offlimits(7)-pmv <= rframes && rframes <= offlimits(7)+pmv) ...
           || (offlimits(8)-pmv <= rframes && rframes <= offlimits(8)+pmv) 
            rframes = randi([0 isiTimeFrames*2]);
        end 
